services:
  db:
    image: mysql:8.0
    container_name: cms-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: course_management
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: cmspassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: cms-app
    depends_on:
      - db
    environment:
      DB_URL: "jdbc:mysql://db:3306/course_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      DB_USERNAME: "cmsuser"
      DB_PASSWORD: "cmspassword"
    ports:
      - "8080:8080"

volumes:
  db_data:
